data:extend{
  {
    type = "item",
    name = "location-combinator",
    icon = "__base__/graphics/icons/constant-combinator.png",
    icon_size = 32,
    subgroup = "circuit-network",
    place_result="location-combinator",
    order = "b[combinators]-d[location-combinator]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "bonus-combinator",
    icon = "__base__/graphics/icons/constant-combinator.png",
    icon_size = 32,
    subgroup = "circuit-network",
    place_result="bonus-combinator",
    order = "b[combinators]-d[bonus-combinator]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "player-combinator",
    icon = "__base__/graphics/icons/constant-combinator.png",
    icon_size = 32,
    subgroup = "circuit-network",
    place_result="player-combinator",
    order = "b[combinators]-d[player-combinator]",
    stack_size = 50,
  },
  }
